// cozyemployee-mesh/snapshots.js
//
// Loads snapshot IDs from snapshots.json and exposes a simple lookup.
// Falls back gracefully to null (fresh Box.create) if snapshots haven't
// been created yet or if a specific one is missing.
//
// snapshots.json is generated by:
//   npx tsx cozyemployee-mesh/scripts/create-snapshots.ts
//
// Format:
//   {
//     "moderator":   { "id": "snap_xxx", "name": "mesh-moderator", ... },
//     "reflect":     { "id": "snap_yyy", ... },
//     "architect":   { "id": "snap_zzz", ... },
//     ...
//   }

const path = require("path");
const fs = require("fs");

const SNAPSHOTS_FILE = path.join(__dirname, "snapshots.json");

let _cache = null;

function loadSnapshots() {
  if (_cache) return _cache;
  try {
    if (fs.existsSync(SNAPSHOTS_FILE)) {
      _cache = JSON.parse(fs.readFileSync(SNAPSHOTS_FILE, "utf-8"));
      const keys = Object.keys(_cache);
      console.log(`[snapshots] Loaded ${keys.length} snapshot(s): ${keys.join(", ")}`);
    } else {
      console.warn(`[snapshots] snapshots.json not found — using fresh Box.create() for all`);
      console.warn(`[snapshots] Run: npx tsx cozyemployee-mesh/scripts/create-snapshots.ts`);
      _cache = {};
    }
  } catch (err) {
    console.error(`[snapshots] Failed to load snapshots.json:`, err.message);
    _cache = {};
  }
  return _cache;
}

/**
 * Get the snapshot ID for a given box key.
 * Returns the snapshot ID string, or null if not available.
 *
 * @param {string} key - e.g. "moderator", "reflect", "architect", "synthesizer"
 * @returns {string|null}
 */
function getSnapshot(key) {
  const snapshots = loadSnapshots();
  const entry = snapshots[key];
  if (!entry) return null;
  return entry.id || null;
}

/**
 * Get full snapshot metadata for a key.
 * @returns {{ id, name, description, packages, createdAt } | null}
 */
function getSnapshotMeta(key) {
  const snapshots = loadSnapshots();
  return snapshots[key] || null;
}

/**
 * List all available snapshot keys.
 * @returns {string[]}
 */
function listSnapshots() {
  return Object.keys(loadSnapshots());
}

/**
 * Invalidate the in-memory cache (e.g. after running create-snapshots).
 */
function reloadSnapshots() {
  _cache = null;
  return loadSnapshots();
}

module.exports = { getSnapshot, getSnapshotMeta, listSnapshots, reloadSnapshots };
